### ISSUE TITLE
Forked pytest broken

### ISSUE THREAD

**Issue by LucienMorey** [thedropbears/pycrescendo#10]
ci runner seems to be broken thanks to ctre at the moment. This just disables that run option for the time being but it should be re-enabled when possible - potentially once they release their official bindings in the coming days.

_Originally posted by @LucienMorey in https://github.com/thedropbears/pycrescendo/issues/9#issuecomment-1880574237_

**Comment by outsidermm** [comment]
Forked pytest is no longer necessary as pytest have max fail of 2
