### ISSUE TITLE
Add skeletons for subsystems

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pycrescendo#13]
A great first task for the rookies...

We know what subsystems we have on the robot, and they will be the `components` in this repo.

Have a read of the `magicbot` docs: https://robotpy.readthedocs.io/en/stable/frameworks/magicbot.html 
Then have a go at creating a component. You should have the function names in there, but they don't have to do anything.

For example, you might have the `Shooter` component, and it might have `shoot()` and `stop()`. These functions don't do anything at the moment, they just `pass`. But at the end of this we'd have a skeleton to build our code on.

**Comment by LucienMorey** [comment]
@DawnDroppingBears @MaxWorrall you guys have both shown some interest in software so far. Maybe one of you wants to take this on?

**Comment by james-ward** [comment]
You can do it one component at a time - you don't have to do it all at once!

**Comment by fotnitfpro000** [comment]
max just pushed another intake scaffold as you were

**Comment by MaxWorrall** [comment]
Made all the scaffolds, they're avaliable for review
https://github.com/thedropbears/pycrescendo/pulls
