### ISSUE TITLE
Move off of pipenv

### ISSUE THREAD

**Issue by auscompgeek** [thedropbears/pycrescendo#16]
Last year we found that `pipenv` didn't generate the same lock file between operating systems. We should converge as a team on a tool that we can _all_ reliably use to manage our dependencies in a virtual environment.

Also, pipenv's locking and dependency resolution doesn't do the right thing either: when I bumped `robotpy-navx` (46024ee0cefd2c7fc6babd88d7b73a6b6b840853), it updated `pyfrc` and `robotpy-installer` too. When I tried to pin them in `[dev-packages]` the resolved packages were still wrong (it included `robotpy-cli` in the lock file, which wasn't a dependency of anything declared).

So far I've seen two popular alternatives that use a lock file: poetry and pdm.

**Comment by james-ward** [comment]
No preference - feel free to choose your favorite @auscompgeek

**Comment by auscompgeek** [comment]
One thing I've found with both poetry and pdm is that they fail to resolve the `robotpy-opencv` platform-specific dependency in the `robotpy` package's [`apriltag`](https://github.com/robotpy/robotpy-meta/blob/3082650313eb509b2419bbff260e187ca82db4f2/apriltag-requirements.txt#L6) and [`cscore`](https://github.com/robotpy/robotpy-meta/blob/3082650313eb509b2419bbff260e187ca82db4f2/cscore-requirements.txt#L7) extras. Unsurprising given both tools aim to create a lock file that works regardless of your platform.

We'll have to list the `robotpy-apriltag` and `robotpy-cscore` dependencies separately in pyproject.toml if we still want them on the roboRIO. No biggie.
