### ISSUE TITLE
Set ramp up/down limits on shooter motors

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pycrescendo#164]
Help to protect the pulleys and belts by not having the controller try to track super abrupt changes in speed.

**Comment by auscompgeek** [comment]
A [voltage ramp rate] would probably do the trick here right?

[voltage ramp rate]: https://api.ctr-electronics.com/phoenix6/release/python/autoapi/phoenix6/configs/index.html#phoenix6.configs.ClosedLoopRampsConfigs.voltage_closed_loop_ramp_period
