### ISSUE TITLE
Align with speaker when trigger pressed

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pycrescendo#22]
When the driver presses the trigger (whatever that is decided to be on the gamepad) the robot should rotate to point at our speaker. Translational control of the robot should still remain with the driver.

You will need to:
* get the current pose of the robot (position and heading)
* get which alliance we are on, and the position of our speaker
* work out the heading the robot needs to rotate to, and set that target
* continue to do this only when the trigger is held

You can also assume that the shooter points out the *rear* of the robot, so we want to point the rear at the speaker.

**Comment by outsidermm** [comment]
This seems like it should be under the movement controller right?

**Comment by auscompgeek** [comment]
Copying the movement controller is not a great idea for something as simple as this. A PID controller on heading would be a much simpler solution.

**Comment by james-ward** [comment]
The "movement controller" from last year is very bad design, and we won't be doing that this year.

This functionality is obviously the beginning of the shooting routine, so it would be appropriate to put it in a controller (state machine).
But I agree with @auscompgeek - the ability to track a heading is just a simple PID loop. And components should be responsible for their own functionality - so the chassis should be able to be told "snap to this heading" and it takes care of the rest.

I think that is enough pieces of the puzzle to be getting on? Let me know what you all come up with.

**Comment by LucienMorey** [comment]
Closed with the merge of #39
