### ISSUE TITLE
Get the simulation going

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pycrescendo#35]
Get the field in the sim, update `physics.py`, make simulation great again.

**Comment by auscompgeek** [comment]
> Get the field in the sim

I would wait for the next WPILib release, which should get us this for free.

**Comment by james-ward** [comment]
> > Get the field in the sim
> 
> I would wait for the next WPILib release, which should get us this for free.

Turns out it is already there!

**Comment by auscompgeek** [comment]
> Turns out it is already there!

Yup, but the dimensions are wrong in Glass.
