### ISSUE TITLE
Make component/controller names consistent

### ISSUE THREAD

**Issue by mlists** [thedropbears/pycrescendo#46]
Currently we have the components ShooterComponent, Intake, Climber and Chassis while we have the controllers Shooter and Climber again. We should decide on a naming convention and stick to it.

**Comment by auscompgeek** [comment]
I'd be a fan of making the controller names present tense verbs (e.g. `shooting: ShootingController`)

**Comment by james-ward** [comment]
I don't care so much about the variable names, but in the past we have called the components `XyzComponent` and the controller `Xyz` on the basis that stuff should only be interacting with the controller, as a rule.
