### ISSUE TITLE
Shooter injection will fail

### ISSUE THREAD

**Issue by mlists** [thedropbears/pycrescendo#47]
Calling the shoot command causes the should_inject flag to be set for only a single control loop, this will be too fast for the injection to complete. We can either use a sensor to check that the note is gone or just use a longer timer.

**Comment by fotnitfpro000** [comment]
how come the flag goes false despite the button being pressed? Doesnt the if statement get called regularly which sets the flag to true?

**Comment by mlists** [comment]
If the shoot command is called by code e.g. autonomous it will only be set for a single loop. Even in teleop, we don't want the drivers to have to think about whether they have held the button down for long enough.

**Comment by auscompgeek** [comment]
This should be handled in the state machine, if you ask me.
