### ISSUE TITLE
Upgrade shooter component to handle inclination set points

### ISSUE THREAD

**Issue by LucienMorey** [thedropbears/pycrescendo#48]
Lorenzo is planning a shooter upgrade and our code will need to match this. They are adding additional functionality to the prototype to raise the inclination angle of a shot.

Steps in my head are as follows
- [ ] Add new inclination motor and encoder to shooter component
- [ ] Add new ```set_inclination``` class method to the shooter component that will take an angle set point
- [ ] Add position controller to class constructor which will can generate and dispatch motor commands during ```execute```
- [ ] Add new ```at_inclination``` feedback method

Additional notes for thought:
- We will likely need to have limit switches on the mechanism to prevent over drive and damage of the mechanism. Speak to the mechanical team about this and where they might fit on the mechanical assembly so they don't break

**Comment by james-ward** [comment]
>     * We will likely need to have limit switches on the mechanism to prevent over drive and damage of the mechanism. Speak to the mechanical team about this and where they might fit on the mechanical assembly so they don't break

No limit switches - just the absolute encoder.
