### ISSUE TITLE
Make climb component not a psuedo state machine

### ISSUE THREAD

**Issue by mlists** [thedropbears/pycrescendo#67]
The way I wrote the climber component is a little bit silly, it is acting almost like a state machine. We should set a speed variable in the deploy/retract functions that will reset to zero and use it to control the motor speed. This would mean the state machine would call deploy/retract in its states rather than just on transition.

**Comment by fotnitfpro000** [comment]
#71

**Comment by mlists** [comment]
Closed by #71
