### ISSUE TITLE
Climber component state machine won't stop at deployed

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pycrescendo#80]
When using the state machine (as is the case in teleop) the state machine will transition to _retract_hook_ as soon as it finished the _extend_hook_ state.
It should stop and wait for the command to retract.

**Comment by mlists** [comment]
Huh, I guess I introduced that in my bugfix. It skipped through when testing before the change so I thought the check was on the wrong state. Button must have been stuck down on the dodgy controller. 🙃

**Comment by james-ward** [comment]
It works fine in test mode, just not teleop
