### ISSUE TITLE
Make a finalised control scheme

### ISSUE THREAD

**Issue by mlists** [thedropbears/pycrescendo#87]
This may have to wait until code is more settled but we are probably pretty close on that front already. Once a drive team has been selected, we should discuss with them how they want to control the robot and then implement those controls.

**Comment by fotnitfpro000** [comment]
[https://github.com/thedropbears/pycrescendo/pull/99](url)

**Comment by SebZanardo** [comment]
<img width="958" alt="control_scheme" src="https://github.com/thedropbears/pycrescendo/assets/97170564/b0505f6a-878a-4284-92b7-7a8316b7ecda">
